# Generated by Django 5.2.2 on 2025-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_remove_test_course_remove_test_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('profesor', 'Profesor')], max_length=20),
        ),
    ]
