# Generated by Django 5.2.2 on 2025-06-07 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='course',
            new_name='cursos',
        ),
    ]
