# Generated by Django 5.2.2 on 2025-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_pegatina_pregunta_respuesta_cursousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
