# Generated by Django 5.2.2 on 2025-06-12 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_testrespondido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pegatina',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='pegatinas', to=settings.AUTH_USER_MODEL),
        ),
    ]
