# Generated by Django 5.2.2 on 2025-06-12 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_pegatina_usuarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_enviados', to=settings.AUTH_USER_MODEL)),
                ('pegatina_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofrecidas', to='cursos.pegatina')),
                ('pegatina_receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deseadas', to='cursos.pegatina')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
