# Generated by Django 5.2.2 on 2025-06-13 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_intercambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos'),
            preserve_default=False,
        ),
    ]
